[[pipelines]]
name = "tests"

[[pipelines.steps]]
name = "test library"
commands = ["""
  pipelight run test-lib --attach
"""]
[[pipelines.steps]]
name = "test modules"
commands = ["""
  pipelight run test-modules --attach
"""]

[[pipelines]]
name = "test-lib"
[[pipelines.steps]]
name = "run lix-unit tests"
commands = ["""
  nix-unit --flake '.#tests'
"""]

[[pipelines]]
name = "test-modules"

[[pipelines.steps]]
name = "build home-merger template flake"
commands = ["""
  pipelight run test-module_home-merger --attach
"""]

[[pipelines.steps]]
name = "build umports template flake"
commands = ["""
  pipelight run test-module_umports --attach
"""]

[[pipelines.steps]]
name = "build networking-privacy template flake"
commands = ["""
  pipelight run test-module_network-privacy --attach
"""]

[[pipelines]]
name = "test-module_home-merger"

[[pipelines.steps]]
name = "run home-merger module tests"
commands = ["""
  nix flake update --flake ./templates/home-merger
  """, """
  nixos-rebuild build \
  --flake './templates/home-merger#default' \
  --override-input nixos-tidy ./
"""]

[[pipelines]]
name = "test-module_umports"

[[pipelines.steps]]
name = "run umports module tests"
commands = ["""
  nix flake update --flake ./templates/umports
  """, """
  nixos-rebuild build \
  --flake './templates/umports#default' \
  --override-input nixos-tidy ./
"""]

[[pipelines]]
name = "test-module_network-privacy"

[[pipelines.steps]]
name = "run networking-privacy module tests"
commands = ["""
  nix flake update --flake ./templates/networking-privacy
  """, """
  nixos-rebuild build \
  --flake './templates/networking-privacy#default' \
  --override-input nixos-tidy ./
"""]
