[[pipelines]]
name = "tests"

[[pipelines.steps]]
name = "lib-tests"
commands = ["""
  pipelight run lib-tests --attach
"""]
[[pipelines.steps]]
name = "module-tests"
commands = ["""
  pipelight run module-tests --attach
"""]

[[pipelines]]
name = "lib-tests"

[[pipelines.steps]]
name = "run lix-unit tests"
commands = ["""
  nix-unit --flake '.#tests'
"""]

[[pipelines]]
name = "module-tests"

[[pipelines.steps]]
name = "run home-merger module tests"
commands = ["""
  nix flake update --flake ./templates/home-merger
  """, """
  nixos-rebuild build \
  --flake './templates/home-merger#default' \
  --override-input nixos-tidy ./
"""]

[[pipelines.steps]]
name = "run umports module tests"
commands = ["""
  nix flake update --flake ./templates/umports
  """, """
  nixos-rebuild build \
  --flake './templates/umports#default' \
  --override-input nixos-tidy ./
"""]
